name: Check for Typos

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@de089481bd65b71b4d02e34ffb3566b6d189333e
        uses: crate-ci/typos@592b36d23c62cb378f6097a292bc902ee73f93ef # version 1.0.4
        with: 
          files: ./deid ./docs/_docs ./docs/README.md ./docs/pages ./examples
